server:
  port: 9090

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: false
        default-page-size: 5

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mhlog
    username: sa
    password:
    driver-class-name: org.h2.Driver